### ISSUE TITLE
Seems to crash with mbrola voices

### ISSUE THREAD

**Issue by smathieson** [sugarlabs/gst-plugins-espeak#2]
Hello,

Gstreamer-espeak seems to crash with mbrola voices.

To reproduce simply use any (almost) mbrola voice:
```
GST_DEBUG=espeak:5 gst-launch-1.0 espeak text="probando" voice=mb-es2 ! autoaudiosink
```
Sorry if this is not an issue with your plugin, however I do not know how to debug gstreamer stuff.

Any help would be appreciated please.

Error is as follows:
```
(gst-launch-1.0:15416): GStreamer-CRITICAL **: gst_memory_new_wrapped: assertion 'offset + size <= maxsize' failed
(gst-launch-1.0:15416): GStreamer-CRITICAL **: gst_mini_object_lock: assertion 'object != NULL' failed
(gst-launch-1.0:15416): GStreamer-CRITICAL **: gst_memory_get_sizes: assertion 'mem != NULL' failed
(gst-launch-1.0:15416): GStreamer-CRITICAL **: gst_mini_object_ref: assertion 'mini_object != NULL' failed
(gst-launch-1.0:15416): GStreamer-CRITICAL **: gst_mini_object_unlock: assertion 'object != NULL' failed
(gst-launch-1.0:15416): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
mbrola: 
mbrola: ced with _-_
```

**Comment by quozl** [comment]
Thanks, that's interesting.  What version of gst-plugins-espeak, or what git hash?

**Comment by smathieson** [comment]
Tried with latest version in debian sid, 4.0.3 and with 125c6c0. Same result.

Note: it DOES work with SOME mbrola voices, for example mb-mx1. I suspect it has something to do with the espeak-ng phonemes that are missing? Espeak seems to handle some things better than espeak-ng.

**Comment by quozl** [comment]
Thanks, I've tried to reproduce with Ubuntu 18.04 with gstreamer1.0-espeak 0.4.0-3, espeak 1.48.04, and espeak-ng 1.49.1, and the symptom is repeating voice that I have to interrupt.

Is that what you mean by seems to crash, or was there another symptom?

Here's the script(1) log;

```
guest@guest:~$ GST_DEBUG=espeak:5 gst-launch-1.0 espeak text="probando" voice=mb-es2 ! autoaudiosink
Setting pipeline to PAUSED ...
0:00:00.219054284  2760 0x5557534c6ea0 DEBUG                 espeak gstespeak.c:277:gst_espeak_start: gst_espeak_start
Pipeline is PREROLLING ...

(gst-launch-1.0:2760): GStreamer-WARNING **: gstpad.c:5138:store_sticky_event:<espeak0:src> Sticky event misordering, got 'caps' before 'stream-start'

(gst-launch-1.0:2760): GStreamer-WARNING **: gstpad.c:5138:store_sticky_event:<sink:proxypad0> Sticky event misordering, got 'caps' before 'stream-start'

(gst-launch-1.0:2760): GStreamer-WARNING **: gstpad.c:5138:store_sticky_event:<autoaudiosink0-actual-sink-pulse:sink> Sticky event misordering, got 'caps' before 'stream-start'

(gst-launch-1.0:2760): GStreamer-WARNING **: gstpad.c:5138:store_sticky_event:<autoaudiosink0:sink> Sticky event misordering, got 'caps' before 'stream-start'
Redistribute latency...
mbrola: 
mbrola: 
mbrola: 
mbrola: 
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstPulseSinkClock

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_memory_new_wrapped: assertion 'offset + size <= maxsize' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_lock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_memory_get_sizes: assertion 'mem != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unlock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
mbrola: 
mbrola: 

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_memory_new_wrapped: assertion 'offset + size <= maxsize' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_lock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_memory_get_sizes: assertion 'mem != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unlock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
mbrola: 
mbrola: 

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_memory_new_wrapped: assertion 'offset + size <= maxsize' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_lock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_memory_get_sizes: assertion 'mem != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unlock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
mbrola: 
mbrola: 

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_memory_new_wrapped: assertion 'offset + size <= maxsize' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_lock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_memory_get_sizes: assertion 'mem != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unlock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
mbrola: 
mbrola: 

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_memory_new_wrapped: assertion 'offset + size <= maxsize' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_lock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_memory_get_sizes: assertion 'mem != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unlock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
mbrola: 
mbrola: 

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_memory_new_wrapped: assertion 'offset + size <= maxsize' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_lock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_memory_get_sizes: assertion 'mem != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_ref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unlock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
mbrola: Warning: r-o/ unkown, replaced with _-_
mbrola: Warning: d-o/ unkown, replaced with _-_
^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:03.147916176
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
0:00:03.393525456  2760 0x5557534c6ea0 DEBUG                 espeak gstespeak.c:285:gst_espeak_stop: gst_espeak_stop

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_memory_new_wrapped: assertion 'offset + size <= maxsize' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_lock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unlock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_memory_new_wrapped: assertion 'offset + size <= maxsize' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_lock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unlock: assertion 'object != NULL' failed

(gst-launch-1.0:2760): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
Setting pipeline to NULL ...
Freeing pipeline ...
guest@guest:~$ 
```

**Comment by smathieson** [comment]
Thats exactly what I mean, sometimes there is no voice at all, but just keeps trying.

**Comment by smathieson** [comment]
I think it might have something to do with mbrola messages, since it seems to crash and re-start the pipeline every time there is an mbrola warning message.

mbrola: Warning: r-o/ unkown, replaced with _-_

Try this:
GST_DEBUG=espeak:5 gst-launch-1.0 espeak text="pr-oband-o" voice=mb-mx1 ! autoaudiosink

It works, although it is mistaken. Espeak-ng works from command line as well.

**Comment by quozl** [comment]
I'm able to reproduce the same repeating voice pattern with standard espeak voices, so I think we can ignore mbrola.

**Comment by smathieson** [comment]
Ah, so probably something to do with the phonemes, the funny thing is why does it work with "pr-oband-o"?

**Comment by quozl** [comment]
Yes, good question.  In my tests it reproduces with certain phrases, and is more likely if a longer phrase is spoken first in the same application.  Application I'm testing is https://github.com/sugarlabs/speak

**Comment by smathieson** [comment]
The error message seems to suggest the memory is not enough?

"assertion 'offset + size <= maxsize' failed"

I really don't know anything about how gstreamer works though.

**Comment by quozl** [comment]
Yes, that looks like it might be important.  Perhaps caused by [espeak.c line 270](https://github.com/sugarlabs/gst-plugins-espeak/blob/master/src/espeak.c#L270)?

Sorry, I don't know much about how GStreamer works either.

**Comment by ndufresne** [comment]
Applicable to all GLib assertions, set the env G_DEBUG=fatal_criticals in order to make it crash at the point and get a backtrace in GDB.

**Comment by quozl** [comment]
Thanks.

```
#0  0x00007ffff7587961 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0 
#1  0x00007ffff7588c4b in g_logv () at /lib/x86_64-linux-gnu/libglib-2.0.so.0 
#2  0x00007ffff7588d9f in g_log () at /lib/x86_64-linux-gnu/libglib-2.0.so.0 
#3  0x00007ffff7ad1754 in gst_memory_new_wrapped () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 
#4  0x00007ffff7adc01a in gst_buffer_new_wrapped_full () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 
#5  0x00007ffff558a738 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstespeak.so 
#6  0x00007ffff558bb4a in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstespeak.so 
#7  0x00007ffff50e66e9 in  () at /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0 
#8  0x00007ffff50e83cb in  () at /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0 
#9  0x00007ffff7b46df9 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 
#10 0x00007ffff75aa010 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0 
#11 0x00007ffff75a9645 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0 
#12 0x00007ffff731f7fc in start_thread (arg=0x7fffeee44700) at pthread_create.c:465 
#13 0x00007ffff704cb0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95 
```
